
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class ListWithDiscount extends javax.swing.JDialog {

    /**
     * Creates new form ListWithDiscount
     */
    public ListWithDiscount(java.awt.Dialog parent, boolean modal,int id_client) {
        super(parent, modal);
//        int id_client=15766;

        try{
            String SQL=String.format("select trim(s.name),trim(g.name),d.disc from sklad s,discount d,(select g.id_group as id_group, SYS_CONNECT_BY_PATH(trim(g.name),' // ') as name from groupid g start with g.parent_group is null connect by g.parent_group= prior g.id_group union select -2 as id_group, 'Все группы' as name from dual) g where d.ID_CLIENT=%s and s.ID_SKL = d.ID_SKL and nvl(d.ID_GROUP,-2)=g.id_group order by s.name,g.name", id_client);
            ResultSet rs=DataSet.QueryExec(SQL, false);
            Vector<String> line=new Vector<String>(0);
//            String[] line=new String[3];
            Vector<Vector<String>> lines =new Vector<Vector<String>>(0);
            while (rs.next()){
                line.add(rs.getString(1));
                line.add(rs.getString(2));
                line.add(rs.getString(3));
                lines.add(new Vector(line));
                line.clear();
            }
            Vector<String> columnName=new Vector<String>(0);
            columnName.add("Склад");
            columnName.add("Группа");
            columnName.add("Скидка");
            model=new DefaultTableModel(lines, columnName);
        }catch(Exception ex){ex.printStackTrace();}
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        discountScrool = new javax.swing.JScrollPane();
        discountTable = new javax.swing.JTable();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);

        discountTable.setModel(model);
        discountScrool.setViewportView(discountTable);

        closeButton.setText("Закрыть");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(discountScrool, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(closeButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(discountScrool, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_closeButtonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JScrollPane discountScrool;
    private javax.swing.JTable discountTable;
    // End of variables declaration//GEN-END:variables
    
    DefaultTableModel model;

}

